// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdsJJt68p-Xe5FhSZegTlidf2aLz5I7hI',
    appId: '1:452745461636:web:5637a617a90f16fd88e7d1',
    messagingSenderId: '452745461636',
    projectId: 'aplikasi-makanan-kampus-online',
    authDomain: 'aplikasi-makanan-kampus-online.firebaseapp.com',
    databaseURL: 'https://aplikasi-makanan-kampus-online-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-makanan-kampus-online.appspot.com',
    measurementId: 'G-X44GTMZK64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ82tADHn5QBv8pS9LjVZpU800BicWCNk',
    appId: '1:452745461636:android:312a6188ff9d9c5388e7d1',
    messagingSenderId: '452745461636',
    projectId: 'aplikasi-makanan-kampus-online',
    databaseURL: 'https://aplikasi-makanan-kampus-online-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-makanan-kampus-online.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXdv67NpQNtaDiLsXvhsRdw7HJV-u295k',
    appId: '1:452745461636:ios:f2607dec2684ee5288e7d1',
    messagingSenderId: '452745461636',
    projectId: 'aplikasi-makanan-kampus-online',
    databaseURL: 'https://aplikasi-makanan-kampus-online-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-makanan-kampus-online.appspot.com',
    iosBundleId: 'com.example.projectUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXdv67NpQNtaDiLsXvhsRdw7HJV-u295k',
    appId: '1:452745461636:ios:f2607dec2684ee5288e7d1',
    messagingSenderId: '452745461636',
    projectId: 'aplikasi-makanan-kampus-online',
    databaseURL: 'https://aplikasi-makanan-kampus-online-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-makanan-kampus-online.appspot.com',
    iosBundleId: 'com.example.projectUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdsJJt68p-Xe5FhSZegTlidf2aLz5I7hI',
    appId: '1:452745461636:web:9e8235cc845e4c1b88e7d1',
    messagingSenderId: '452745461636',
    projectId: 'aplikasi-makanan-kampus-online',
    authDomain: 'aplikasi-makanan-kampus-online.firebaseapp.com',
    databaseURL: 'https://aplikasi-makanan-kampus-online-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-makanan-kampus-online.appspot.com',
    measurementId: 'G-47T1TY959J',
  );
}
